export const DEFAULT = 'Home/DEFAULT'
export const FILTER = 'Home/FILTER'
export const SEARCH = 'Home/SEARCH'
export const ADD = 'Home/ADD'
export const UPDATE_ITEM = 'Home/UPDATE_ITEM'
export const DELETE_ITEM = 'Home/DELETE_ITEM'
export const SET_DATA = 'Home/SET_DATA'